version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: hirfa
      # You should definitely change the password in production
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - hirfa-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - dev

  nginx:
    build:
      context: docker/nginx
    restart: on-failure
    volumes:
      - ./:/var/www/server:cached
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/server.conf:cached
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - dev
  php:
    build:
      context: docker/php
    restart: on-failure
    volumes:
      - .:/var/www/hirfa:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - database
    networks:
      - dev
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - dev
networks:
  dev:
volumes:
  hirfa-data:
